version: "3.9"

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mrtj458
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecurerootpassword
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mrtj458
    restart: always

  phpapache:
    depends_on:
      - db
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    restart: always

volumes:
  db_data:
    driver: local
